SRCS = \
force.cpp \
forceGravity.cpp \
forceInput.cpp \
gameBase.cpp \
gameOptions.cpp \
gameState.cpp \
input.cpp \
inputLiveHandler.cpp \
inputPlayback.cpp \
inputRecord.cpp \
main.cpp \
object.cpp \
objectBackground.cpp \
objectFactory.cpp \
objectPlayer.cpp \
objectRadiusBlock.cpp \
timer.cpp \
vec.cpp \
window.cpp 
