// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "stdafx.h"
#include "GUI_layeroptions.h"

Fl_Menu_Button *mnuLayers=(Fl_Menu_Button *)0;

static Fl_Check_Button *chkDisplayAllLayers=(Fl_Check_Button *)0;

Fl_Window* FLTK_DisplayLayerOptions() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(339, 299);
    w = o;
    { Fl_Menu_Button* o = mnuLayers = new Fl_Menu_Button(10, 30, 240, 20, "Layers");
      o->callback((Fl_Callback*)OnLayerSelectionChanged);
    }
    { Fl_Box* o = new Fl_Box(0, 0, 340, 20, "Layer Options");
      o->box(FL_THIN_UP_FRAME);
    }
    new Fl_Button(250, 30, 80, 20, "New layer");
    { Fl_Check_Button* o = chkDisplayAllLayers = new Fl_Check_Button(10, 55, 320, 20, "Display All Layers");
      o->down_box(FL_EMBOSSED_BOX);
    }
    o->end();
  }
  return w;
}
