// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef GUI_layeroptions_h
#define GUI_layeroptions_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Button.H>
extern void OnLayerSelectionChanged(Fl_Menu_Button*, void*);
extern Fl_Menu_Button *mnuLayers;
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
Fl_Window* FLTK_DisplayLayerOptions();
#endif
