#!/bin/bash

# Dom's custom script to generate the correct output for the NSIS 
# installer script
#
# (c) 2006 Dominic Cerquetti <binary1230 AT yahoo DOT com>

# variables you can modify

output_file="installer.nsi"

template_file="installer-files/installer.template.nsi"

installerfile_part1="installer-files/installer_part1.txt"
installerfile_part2="installer-files/installer_part2.txt"
installerfile_part3="installer-files/installer_part3.txt"
tmpfile="installer-files/tmpfile"

if [ "$#" != 1 ]; then
	echo "ERROR: Expected a path to distributable dir (e.g. dist/win32/ninjas-engine-xyz/)"
	exit -1;
fi

dos2unix $template_file

DIST_DIR=$1/

msg1="; ---------- GENERATED BY makensis.sh, DO NOT EDIT -------------"
msg2="; ---------- DONE GENERATED -------------"

echo $msg1 > $installerfile_part1
echo $msg1 > $installerfile_part2
echo $msg1 > $installerfile_part3

find "$DIST_DIR" -type d -printf "%P\n" | grep -v '\.svn' | while read -r dir; do
	
	echo '	SetOutPath "$INSTDIR\'$dir'"' >> $installerfile_part1

	if [ "$dir" != "" ]; then
		echo '	RMDir "$INSTDIR\'$dir'"' >> $installerfile_part3
	fi

	find "$DIST_DIR/$dir" -maxdepth 1 -not \( -type d -o -name .svn  \) -printf "%f\n" | while read -r file; do
		
		echo '	File "'"$DIST_DIR$dir/$file"'"' >> $installerfile_part1

		echo '	Delete "$INSTDIR\'"$dir/$file"'"' >> $installerfile_part2

	done

done 
		
echo '	RMDir "$INSTDIR\"' >> $installerfile_part3

echo $msg2 >> $installerfile_part1
echo $msg2 >> $installerfile_part2
echo $msg2 >> $installerfile_part3

cat $installerfile_part1 | sed 's+/+\\+g' | sed 's+\\\\+\\+g' > $tmpfile
mv -f $tmpfile $installerfile_part1

cat $installerfile_part2 | sed 's+/+\\+g' | sed 's+\\\\+\\+g' > $tmpfile
mv -f $tmpfile $installerfile_part2

cat $installerfile_part3 | sed 's+/+\\+g' | sed 's+\\\\+\\+g' > $tmpfile
mv -f $tmpfile $installerfile_part3 

echo "; Automatically generated NSI file from makensis.sh (Pirates Vs Ninjas)" > $output_file

# files generated, now replace them
cat "$template_file"  | while read -r line; do
	tmp=`echo $line | cut -f 1 -d ':'`

	# if the line starts with "; -- REPLACE:" then a filename comes after
	# it which we should replace here
	if [ "$tmp" == "; -- REPLACE" ]; then
		filename=`echo $line | cut -f 2 -d ':'`
		cat "$filename" >> $output_file
	else
		echo $line >> $output_file
	fi
done

rm -f $installerfile_part1 $installerfile_part2 $installerfile_part3 $tmpfile
